channels:
  - conda-forge
  - defaults
dependencies:
  - imageio=2.4
  - ipython
  - jupyter
  - notebook
  - numpy=1.15
  - opencv=3.4.3=py36_blas_openblash829a850_200
  - pandas=0.22
  - pillow=5.0
  - python=3.6
  - scikit-image=0.14
  - scikit-learn=0.19
  - scipy=1.1
  - matplotlib=2.2
  - tqdm=4.25
  - seaborn=0.8
  - pip:   
    - dask==0.18.2
    - flake8==3.5.0
    - mccabe==0.6.1
    - pycodestyle==2.3.1
    - pyflakes==1.6.0
    - yapf==0.23.0



