channels:
  - defaults       
  - pytorch    
  - conda-forge
dependencies:
  - cudatoolkit=10.2.89
  - python=3.8.13
  - imageio=2.19.3
  - ipython=8.4.0
  - jupyter=1.0.0
  - notebook=6.4.12
  - numpy=1.21.5
  - opencv=4.4.0
  - pandas=1.4.3
  - pip=22.1.2
  - pillow=9.2.0
  - pytorch=1.12.1
  - scikit-image=0.19
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - matplotlib=3.5.2
  - tqdm=4.64.0
  - seaborn=0.11.2
  - pip:   
    - dask==2022.7.0
    - flake8==5.0.4
    - mccabe==0.7.0
    - pycodestyle==2.9.1
    - pyflakes==2.5.0
    - yapf==0.32.0



