_BASE_: "../../detectron2/configs/Base-RCNN-DilatedC5.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
OUTPUT_DIR: "../output/faster_rcnn_R_101_DC5_3x"
