_BASE_: "../../detectron2/configs/Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_101_C4_3x/138204752/model_final_298dad.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
OUTPUT_DIR: "output/v1_new/faster_rcnn_R_101_C4_1x"
