_BASE_: "../../detectron2/configs/Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_C4_3x/137849393/model_final_f97cb7.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
# OUTPUT_DIR: "../output/faster_rcnn_R_50_C4_1x"
OUTPUT_DIR: "output/v1_new_val/faster_rcnn_R_50_C4_1x"
