_BASE_: "../../detectron2/configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
# (the following values were used in the first paper)
  RPN:
    PRE_NMS_TOPK_TRAIN: 600
    PRE_NMS_TOPK_TEST: 300
    POST_NMS_TOPK_TRAIN: 50
    POST_NMS_TOPK_TEST: 50
    NMS_THRESH: 0.7
  ROI_BOX_HEAD:
    POOLER_SAMPLING_RATIO: 0
    POOLER_RESOLUTION: 14
  BACKBONE:
    FREEZE_AT: 2
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001

INPUT:
  CUSTOM_AUGMENTATIONS: False

OUTPUT_DIR: "output/20230616/faster_rcnn_R_50_FPN_1x"
#
#"output/classic2x_val/faster_rcnn_R_50_FPN_1x"
#"output/classic2x_stopcriteria/faster_rcnn_R_50_FPN_1x"
#
# "output/ortho_val2/faster_rcnn_R_50_FPN_1x"
# "output/ortho_stopcriteria2/faster_rcnn_R_50_FPN_1x"
#
#
# "output/v1_new_val/faster_rcnn_R_50_FPN_1x"
# "output/v1_new_val3/faster_rcnn_R_50_FPN_1x"
# "output/v1_new_final/faster_rcnn_R_50_FPN_1x"
